server.servlet.context-path=/workintech
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_app
spring.datasource.username=postgres
spring.datasource.password=hello123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true